### ISSUE TITLE
RPI: No picture and crackling sound

### ISSUE THREAD

**Issue by gizmo98** [libretro/prosystem-libretro#2]
Are there any special build instructions for linux/RPI? The source compiles fine. Retroarch console output shows no error (loads Prosystem.dat and cartridge without any problem). But then nothing happens. There is a crackling sound if RGUI is opened. There is no change if "7800 BIOS (U).rom" is added.

**Comment by sergiobenrocha2** [comment]
You mean some "pop" sounds? No game audio right?

Maybe it's the same issue in android and others ARM boards. I tested in my S4 mini and odroid u3, got the same thing.

**Comment by joolswills** [comment]
It's an issue with the code and some  assumption somewhere that char is signed by default (which they are not on arm). 

if you build on arm with -fsigned-char it works, but it should be properly fixed in the code. I've not looked in any detail though.

**Comment by sergiobenrocha2** [comment]
Yeah -fsigned-char fix it, thanks!

**Comment by twinaphex** [comment]
To @gizmo98 - can you retest it now?
