### ISSUE TITLE
the updated database.c file I submitted is in the wrong place

### ISSUE THREAD

**Issue by underball** [libretro/prosystem-libretro#26]
I submitted a database.c update last week, and it needs to overwrite the original in the /prosystem-libretro/core/ subfolder, but it is currently in the root folder for this git, so when you compile, the changed aren't being added to executable.

**Comment by twinaphex** [comment]
Updated - 

https://github.com/libretro/prosystem-libretro/commit/399a2317aa86e2a4dfe6632bcf0bfe949ec86e1c
