### ISSUE TITLE
Wrong internal resolution causing scaling issues

### ISSUE THREAD

**Issue by Jamirus238** [libretro/prosystem-libretro#55]
Tested on Windows: Taking a screenshot with GPU screenshot turned off results in a 320x223 shot, but  the scaling settings indicate that the core always uses a 320x240 resolution, stretching the picture vertically.  
This causes obvious problems when you need perfect integer scaling in the vertical direction with e.g. the TVout+interlacing shader:
![Winter Games-210214-161212](https://user-images.githubusercontent.com/56701184/107880527-99153b80-6edf-11eb-8b3e-a88fb6045e61.png)

**Comment by rtomasa** [comment]
I was about opening the same issue. The core always provides wrong 320x240@50Hz in PAL or 320x240@60Hz in NTSC
I found out that proper resolutions can be achieved by manually setting:
```
NTSC
custom_viewport_width = "320"
custom_viewport_height = "223"
PAL
custom_viewport_width = "320"
custom_viewport_height = "272"
```
This info makes impossible to properly use automatic switchres among others

**Comment by rtomasa** [comment]
Submitted a new pull request with the fix. @Jamirus238 if you compile the core with my changes games will be displayed as expected.
