### ISSUE TITLE
Support for Rikki and Vikki

### ISSUE THREAD

**Issue by Flashfire42** [libretro/prosystem-libretro#63]
Is there any chance of support for https://store.steampowered.com/app/893690/Rikki__Vikki/
The ROM seems to be programmed differently to your standard Atari 7800 rom with more info being able to be found In this thread https://atariage.com/forums/topic/285896-rikki-vikki
It claims to only run on BupSystem but if you can remedy this so that people might be able to play it using a Libretro Core that would be excellent

**Comment by Sanaki** [comment]
I did verify it doesn't run when headered at least, so that means a simple database entry won't be sufficient to get it working. Assuming the header patch provided in that thread is correct anyway.

**Comment by Augusto7743** [comment]
That is a commercial game and thus being doesn't wait or demand emulation about it because is no sense and create problems for others emulation projects.

**Comment by Sanaki** [comment]
You do realize people emulate their legally owned games, yeah? There's no problem created by trying to support games, so long as the games themselves are hardware-compatible.

**Comment by LibretroAdmin** [comment]
Pull requests are welcome. There's probably not anyone on the Libretro team with reverse engineering chops for this system.

**Comment by tachimarten** [comment]
I have a branch with complete working support for Rikki & Vikki at: https://github.com/tachimarten/prosystem-libretro/tree/rikki

I plan to polish it up and submit as a PR sometime this week.

**Comment by LibretroAdmin** [comment]
Awesome to hear! Looking forward to it.

**Comment by tachimarten** [comment]
This is now up. https://github.com/libretro/prosystem-libretro/pull/71
